- semi-project/src/main/resources/templates/home/modify.html
- semi-project/src/main/resources/templates/home/no-check.html
- semi-project/src/main/resources/templates/home/no-search.html
#81 
로그인 화면 사원번호, 비밀번호 찾기 링크 수정
어떤 변경 사항이 있나요?
> [24.12.06] 로그인화면 사원번호, 비밀번호 찾기 링크 수정

- semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/NoCheckController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/model/dao/UserMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/model/dto/NoCheckDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/model/dto/NoSearchDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/model/service/NoCheckService.java
- semi-project/src/main/resources/mappers/userMapper.xml
- semi-project/src/main/resources/static/home/css/no-search.css
- semi-project/src/main/resources/templates/home/no-check.html
- semi-project/src/main/resources/templates/home/no-search.html
- semi-project/src/main/resources/templates/home/pass-search.html
#94 
사원번호 찾기 기능을 추가하였습니다
- 부서명, 이름, 이메일 중 입력을 하나라도 안할 시 submit을 할 수 없도록 예외처리 해두었습니다
- 세 가지 모두 입력 후 DB와 일치 할 시에만 사원번호를 안내하도록 하였습니다
- 혹여나 일치하지 않거나 정보가 없을 시 알림창과 함께 동일한 페이지로 redirect 되도록 하였습니다
어떤 변경 사항이 있나요?
> [24.12.08] 사원번호 찾기 기능 추가

- semi-project/src/main/resources/templates/home/no-check.html
#94 
사원번호 찾은 후 로그인 하러가기 html 주소를 수정하였습니다
어떤 변경 사항이 있나요?
> [24.12.08] 사원번호 찾기 기능구현 및 링크 수정

- semi-project/build.gradle
- semi-project/src/main/java/com/ohgiraffers/semiproject/config/SecurityConfig.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/HomeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/PassSearchController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/model/dao/UserMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/model/dto/PassSearchDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/model/service/EmailService.java
- semi-project/src/main/resources/application.yml
- semi-project/src/main/resources/mappers/userMapper.xml
- semi-project/src/main/resources/templates/home.html
- semi-project/src/main/resources/templates/home/fail.html
- semi-project/src/main/resources/templates/home/pass-search.html
#102 
비밀번호 찾기 기능 추가
- 비밀번호 찾기 기능이 추가되었습니다
*사번과 이메일이 DB와 일치해야 임시 비밀번호가 발송됩니다*
*만약 일치하는 정보가 없을 시 알림창으로 안내됩니다*
- 사번 저장기능이 추가 되었습니다
*사번 저장을 체크하고 로그인을 하고 다시 홈으로 이동하면 사번이 저장됩니다*
- 로그인 시 일치하는 정보가 아니라면 알림창으로 안내됩니다
어떤 변경 사항이 있나요?
> [24.12.10] 비밀번호찾기, 로그인 예외처리, 사번저장 기능 구현

- semi-project/src/main/java/com/ohgiraffers/semiproject/config/SecurityConfig.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/UserController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/main/controller/MainController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/main/controller/UserInfoController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/main/model/dto/UserInfoResponse.java
- semi-project/src/main/resources/static/main/css/mainPage.css
- semi-project/src/main/resources/static/main/css/user-info.css
- semi-project/src/main/resources/static/main/js/user-info.js
- semi-project/src/main/resources/templates/main/main.html
#109 
메인페이지 대시보드 및 로그아웃 기능 추가하였습니다
- 로그아웃 버튼 클릭 한 번 더 확인할 수 있게 하였습니다
대시보드 구현했습니다
- 차트JS 라이브러리 사용하여 구현하였습니다 
스프링 시큐리티로 로그인한 정보를 확인할 수 있도록 임시로 메인페이지에 구현해두었습니다
- 추 후 UI 수정할 수 있습니다
어떤 변경 사항이 있나요?
> [24.12.11] 로그인 정보 불러오기 구현(임시)

- semi-project/src/main/java/com/ohgiraffers/semiproject/config/SecurityConfig.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/auth/model/service/MemberService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/PassSearchController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/model/service/EmailService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/main/controller/UserInfoController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/main/model/service/UserInfoService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/CheckInRequestDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/CheckOutRequestDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/ScheduleDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
- semi-project/src/main/resources/mappers/scheduleMapper.xml
- semi-project/src/main/resources/static/main/css/user-info.css
- semi-project/src/main/resources/static/main/js/user-info.js
- semi-project/src/main/resources/templates/main/main.html
#109 
로그인한 사번 기준으로 출퇴근 기능이 구현되었습니다
- 출근하기 버튼을 누르면 현재 시간 기준으로 출근시간이 알림창으로 출력 됩니다
- 초 단위로 지속적으로 시간이 흘러가게 됩니다(다른 페이지에 가서도 시간이 흐를 수 있도록 하였습니다)
- 근무시간이 8시간 이라면 정상으로 저장됩니다 8시간 이상 근무 시 연장으로 DB에 저장됩니다
- 퇴근하기 버튼을 누르면 퇴근한 시간과 총 근무시간이 출력 됩니다
- 퇴근하기 버튼은 출근하기 버튼을 누르지 않으면 실행되지 않도록 하였습니다
로그아웃 기능이 구현되었습니다
- 로그아웃  버튼을 누르면 한 번 알림창으로 안내 후 확인 버튼 누를 시 로그아웃이 됩니다
어떤 변경 사항이 있나요?
> [24.12.12] 출퇴근 DB 저장 기능 및 로그아웃 구현

- semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/dao/BoardMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/service/BoardService.java
- semi-project/src/main/resources/mappers/employeeMapper.xml
없음
코드 일부 수정하였습니다
- BoardService 쪽 select 메소드 추가하였습니다
어떤 변경 사항이 있나요?
> [24.12.12] 코드일부수정

- semi-project/src/main/java/com/ohgiraffers/semiproject/board/controller/BoardController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/dao/BoardMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/service/BoardService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/resources/application.yml
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/mappers/employeeMapper.xml
- semi-project/src/main/resources/static/sidemenu/board/css/board-style.css
- semi-project/src/main/resources/static/sidemenu/board/css/search.css
- semi-project/src/main/resources/static/sidemenu/board/css/title.css
- semi-project/src/main/resources/templates/sidemenu/board/board.html
- semi-project/src/main/resources/templates/sidemenu/board/regist.html
- semi-project/src/main/resources/templates/sidemenu/board/search.html
- semi-project/src/main/resources/templates/sidemenu/board/title.html
- semi-project/src/main/resources/templates/sidemenu/board/update.html
- semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
- semi-project/src/main/resources/templates/sidemenu/employee/employee.html
- semi-project/src/main/resources/templates/sidemenu/employee/empregist.html
#126 
게시판 검색해서 나오는기능, 게시판 css, 직원 전체조회, 직원 상세조회
어떤 변경 사항이 있나요?
> 직원정보조회,상세조회

- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleApiController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/ScheduleDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
- semi-project/src/main/resources/mappers/scheduleMapper.xml
- semi-project/src/main/resources/static/main/css/main-style.css
- semi-project/src/main/resources/static/main/css/slide-bar.css
- semi-project/src/main/resources/static/main/js/user-info.js
- semi-project/src/main/resources/static/sidemenu/schedule/css/schedule-style.css
- semi-project/src/main/resources/static/sidemenu/schedule/js/calendar.js
- semi-project/src/main/resources/templates/sidemenu/schedule/schedule.html
근태관리 페이지 캘린더 및 근태정보 DB 연결해두었습니다
어떤 변경 사항이 있나요?
> [24.12.12] 캘린더 추가, 근태DB연결

- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
- semi-project/src/main/resources/mappers/animalMapper.xml
- semi-project/src/main/resources/static/sidemenu/animals/css/adoptionComplete-style.css
- semi-project/src/main/resources/static/sidemenu/animals/css/animals-insert-style.css
- semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
- semi-project/src/main/resources/templates/sidemenu/animals/adoptionComplete.html
- semi-project/src/main/resources/templates/sidemenu/animals/animals.html
- semi-project/src/main/resources/templates/sidemenu/animals/insert.html
> [24.12.13]구조동물조회기능추가

- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleApiController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/CheckInResponseDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/CheckOutResponseDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/VacationDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
- semi-project/src/main/resources/mappers/scheduleMapper.xml
- semi-project/src/main/resources/static/main/js/user-info.js
- semi-project/src/main/resources/static/sidemenu/schedule/css/schedule-style.css
- semi-project/src/main/resources/static/sidemenu/schedule/js/checkInOut.js
- semi-project/src/main/resources/static/sidemenu/schedule/js/user-info.js
- semi-project/src/main/resources/templates/main/main.html
- semi-project/src/main/resources/templates/sidemenu/schedule/schedule.html
없음
근태관리 페이지를 구현하였습니다
- 메인페이지에서 출근버튼을 누르면 근태관리 측에서도 동일하게 타이머가 흐릅니다
- 사원의 휴가와 연차 갯수를 확인할 수 있습니다
어떤 변경 사항이 있나요?
> [24.12.13] 근태관리(출퇴근 시간, 휴가 갯수, DB연결 타이머 연결)

- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/EmployeeJoinListDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/AttendanceAPIController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleApiController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/AttendanceRequest.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/ScheduleDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/mappers/scheduleMapper.xml
- semi-project/src/main/resources/static/sidemenu/schedule/css/attendance.css
- semi-project/src/main/resources/static/sidemenu/schedule/js/attedance.js
- semi-project/src/main/resources/static/sidemenu/schedule/js/calendar.js
- semi-project/src/main/resources/static/sidemenu/schedule/js/getAttendance.js
- semi-project/src/main/resources/templates/sidemenu/schedule/attendance-request.html
- semi-project/src/main/resources/templates/sidemenu/schedule/schedule.html
https://github.com/1995-s-Project/1995-s_GroupWare/issues/136
https://github.com/1995-s-Project/1995-s_GroupWare/issues/137
근태수정 요청이 일부 구현되었습니다
- 수정요청 날짜와 구분(출근수정, 퇴근수정) 을 선택하면 수정 전 근태시간 인풋박스에 자동으로 DB에서 가져오도록 하였습니다
- 수정 후 근태시간은 직접 오전 오후 선택하여 시간을 입력한 다음 관리자 사번 선택, 사유작성까지 해야 폼을 제출할 수 있도록 알림 처리 해두었습니다
- 관리자 사번은 버튼을 추가하여 현재 DB에 저장되있는 직원 정보를 전부 불러온 뒤 원하는 사원을 선택 하면 관리자 사번을 추가할 수 있게 구현하였습니다
어떤 변경 사항이 있나요?
> [24.12.15] 근태수정UI 및 DB 연결(중간Merge)

- semi-project/src/main/java/com/ohgiraffers/semiproject/config/DateUtil.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/AttendanceAPIController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
- semi-project/src/main/resources/mappers/scheduleMapper.xml
- semi-project/src/main/resources/static/sidemenu/schedule/css/attendance.css
- semi-project/src/main/resources/static/sidemenu/schedule/js/selectAttendanceRequest.js
- semi-project/src/main/resources/templates/sidemenu/schedule/attendance-request.html
https://github.com/1995-s-Project/1995-s_GroupWare/issues/136
https://github.com/1995-s-Project/1995-s_GroupWare/issues/137
근태수정 목록 기능이 추가되었습니다
- 근태 수정 등록을 하면 근태수정 목록에 자동으로 추가가 됩니다
- 등록했던 정보가 한 눈으로 볼 수 있게 해두었으며 선택 할 시 모달 창으로 근태사유가 나오도록 하였습니다
- 실수로 올린 근태수정은 삭제를 할 수 있도록 하였으며 여러개 선택 후 삭제하기를 누르면 해당 목록이 삭제되며
- DB 저장 값도 Null 로 설정됩니다
- 관리자가 확인중, 승인됨, 반려됨 등 선택에 따라 라벨로 각각 표시가 될 수 있도록 하였습니다
어떤 변경 사항이 있나요?
> [24.12.15] 근태수정 기능 추가

- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/resources/mappers/empMapper.xml
#152 
머지 후 오류나서 코드 일부 수정하였습니다
EmployeeService 클래스 -> empAllSelect() 메소드 
emp 맵퍼 </select> 추가
어떤 변경 사항이 있나요?
> [24.12.15] 코드 일부 수정

- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/InventoryDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
- semi-project/src/main/resources/mappers/animalMapper.xml
- semi-project/src/main/resources/static/sidemenu/animals/css/adoptionComplete-style.css
- semi-project/src/main/resources/static/sidemenu/animals/css/adoptionDetailAnimal-style.css
- semi-project/src/main/resources/templates/sidemenu/animals/adoptionComplete.html
- semi-project/src/main/resources/templates/sidemenu/animals/adoptionDetailAnimal.html
- semi-project/src/main/resources/templates/sidemenu/animals/animals.html
- semi-project/src/main/resources/templates/sidemenu/animals/stock.html
#151 
재고관리 조회기능
어떤 변경 사항이 있나요?
> [24.12.15]재고관리조회

- semi-project/src/main/resources/static/sidemenu/schedule/js/calendar.js
없음
calendar.js 날짜 포맷팅 하는 과정에서 오류가 발견되어 코드 수정하였습니다
어떤 변경 사항이 있나요?
> [24.12.16] 캘린더 js Date 날짜 포맷팅 수정

- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/resources/static/sidemenu/employee/css/empdetail.css
- semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
없음
직원상세조회 댓글코드 일부수정 및 완료
어떤 변경 사항이 있나요?
> 24.12.16댓글완료

- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/CommentDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/static/sidemenu/employee/css/empdetail.css
- semi-project/src/main/resources/static/sidemenu/facilities/css/facilities-style.css
- semi-project/src/main/resources/templates/sidemenu/employee/delete.html
- semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
- semi-project/src/main/resources/templates/sidemenu/facilities/facilities.html
> <24.12.16 시설물>

- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/AnimalDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/InventoryDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
- semi-project/src/main/resources/mappers/animalMapper.xml
- semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
- semi-project/src/main/resources/static/sidemenu/animals/css/stock-style.css
- semi-project/src/main/resources/templates/sidemenu/animals/animals.html
- semi-project/src/main/resources/templates/sidemenu/animals/insert.html
- semi-project/src/main/resources/templates/sidemenu/animals/stock.html
#160 
재고조회 및 구조동물 카테고리 CSS, 비동기처리
어떤 변경 사항이 있나요?
> [24.12.16]재고조회 및 구조동물 카테고리 CSS, 비동기처리

- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
- semi-project/src/main/resources/static/sidemenu/animals/css/adoptionComplete-style.css
- semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
- semi-project/src/main/resources/templates/sidemenu/animals/animals.html
- semi-project/src/main/resources/templates/sidemenu/animals/stock.html
#168
재고수량 수정 완료 알림창
어떤 변경 사항이 있나요?
> [24.12.16]재고수량 수정 완료 알림창

- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerApprovalAPIController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerApprovalController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/ApprovalUserDTO.java
- semi-project/src/main/resources/static/sidemenu/approval/css/vacation-form.css
- semi-project/src/main/resources/static/sidemenu/approval/js/vacation-form.js
- semi-project/src/main/resources/templates/sidemenu/approval/vacation-form.html
- semi-project/src/main/resources/templates/sidemenu/manager/employeeRegister.html
- semi-project/src/main/resources/templates/user/signup.html
https://github.com/1995-s-Project/1995-s_GroupWare/issues/157
https://github.com/1995-s-Project/1995-s_GroupWare/issues/158
연차 휴가 신청서 UI 구현 및 직원벙보 DB 연결 작업하였습니다
어떤 변경 사항이 있나요?
> [24.12.17] 관리자 결재함 임시구현

- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
- semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
- semi-project/src/main/resources/templates/sidemenu/animals/animals.html
#172
동물리스트 게시판 형식에서 카드 형식으로 수정하였습니다.
어떤 변경 사항이 있나요?
> [24.12.17]구조동물 css 대폭 수정!!

- semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
- semi-project/src/main/resources/templates/sidemenu/adoption/adoption.html
#172 
구조동물 등록, 삭제 버튼 CSS 수정했습니다
어떤 변경 사항이 있나요?
> [24.12.17]구조동물 등록, 삭제 버튼 CSS

- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/MailDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
- semi-project/src/main/resources/mappers/emailMapper.xml
- semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
- semi-project/src/main/resources/templates/sidemenu/mail/mail.html
#171 
시설물 관리를 삭제 및 쪽지기능 발현해보기
어떤 변경 사항이 있나요?
> <24.12.17 이메일기능>

- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/EmployeeDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/MailDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
- semi-project/src/main/resources/mappers/emailMapper.xml
- semi-project/src/main/resources/static/sidemenu/board/css/board-style.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
- semi-project/src/main/resources/templates/sidemenu/mail/mail.html
#181 
쪽지 기능을 눌렀을때 전체조회와 창 띄우기
어떤 변경 사항이 있나요?
> <24.12.18쪽지전체조회>

- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/controller/AdoptionController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dao/AdoptionMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dto/AdoptionDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/service/AdoptionService.java
- semi-project/src/main/resources/mappers/animalAdopterMapper.xml
- semi-project/src/main/resources/static/sidemenu/adoption/css/adoption-style.css
- semi-project/src/main/resources/templates/sidemenu/adoption/adoption.html
#182 , #180 
입양진행중, 입양완료, 입양취소 탭기능으로 조회할 수 있는 기능
어떤 변경 사항이 있나요?
> [24.12.18]입양진행중,입양완료,입양취소 조회

- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerApprovalController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dao/ManagerApprovalMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/service/ManagerApprovalService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleApiController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
- semi-project/src/main/resources/mappers/managerApproval.xml
- semi-project/src/main/resources/mappers/scheduleMapper.xml
- semi-project/src/main/resources/static/sidemenu/approval/css/vacation-form.css
- semi-project/src/main/resources/static/sidemenu/manager/js/approval-list.js
- semi-project/src/main/resources/static/sidemenu/schedule/js/calendar.js
- semi-project/src/main/resources/templates/sidemenu/approval/readVacRequest.html
https://github.com/1995-s-Project/1995-s_GroupWare/issues/157
https://github.com/1995-s-Project/1995-s_GroupWare/issues/158
연차 휴가 신청서가 구현되었습니다
- 연차 휴가 신청서 작성 시 DB와 연결해서 현재 로그인한 사번과 부서명 직급을 자동으로 불러오게 하였습니다
- 어떤 관리자(상급자) 에게 기안을 올릴 건지 모달창으로 구현해 확인 후 선택할 수 있습니다(부서명, 직급 필터링 가능)
- 휴가 종류(연차 or 휴가)를 선택하고 시작일정과 끝나는 일정을 선택하면 연차 및 휴가 일정에 대한 총 일 수를 계산하여 보여주도록 하였습니다 
- 휴가 사유까지 작성 후 등록하게 되면 선택한 관리자 사번과 대표 사번에게 자동으로 기안이 제출됩니다
(모든 필드를 입력하지 않으면 등록할 수 없도록 알림창을 구현해 두었습니다)
- 대표 사번은 앞서 관리자가 먼저 승인을 누르지 않으면 승인 또는 반려를 선택할 수 없도록 로직을 구현하였습니다
- 관리자 사번은 대기중인 결재 기안들을 확인 후 승인 또는 반려를 할 수 있습니다
- 관리자가 승인을 누르면 진행 상태에서 대기중에서 진행중으로 바뀌게 되며 도장 이미지가 찍히도록 하였습니다
- 추가로 승인 이 후에는 대표 사번에게도 승인 또는 반려할 수 있도록 권한이 부여됩니다
- 관리자가 만약 반려를 누른다면 전체 진행상태가 반려로 바뀌게 되며 대표 사번이 굳이 추가로 반려처리를 안해도 되도록 로직을 구현하였습니다
- 관리자 승인, 대표도 승인을 누른다면 전체 진행상태가 진행중에서 …
> [24.12.19] 연차 휴가 로직 구현

- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/controller/AdoptionController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dao/AdoptionMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/service/AdoptionService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/CommentDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/controller/MyPageController.java
- semi-project/src/main/resources/mappers/animalAdopterMapper.xml
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/static/sidemenu/adoption/css/adoptCanceledDetail-style.css
- semi-project/src/main/resources/static/sidemenu/adoption/css/adoptCompletedDetail-style.css
- semi-project/src/main/resources/static/sidemenu/adoption/css/adoptingDetail-style.css
- semi-project/src/main/resources/static/sidemenu/adoption/css/adoption-style.css
- semi-project/src/main/resources/static/sidemenu/mypage/css/myComments-style.css
- semi-project/src/main/resources/static/sidemenu/mypage/css/myMails-style.css
- semi-project/src/main/resources/static/sidemenu/mypage/css/myPosts-style.css
- semi-project/src/main/resources/templates/sidemenu/adoption/adoptCanceledDetail.html
- semi-project/src/main/resources/templates/sidemenu/adoption/adoptCompletedDetail.html
- semi-project/src/main/resources/templates/sidemenu/adoption/adoptingDetail.html
- semi-project/src/main/resources/templates/sidemenu/mypage/myComments.html
- semi-project/src/main/resources/templates/sidemenu/mypage/myMails.html
- semi-project/src/main/resources/templates/sidemenu/mypage/myPosts.html
#192 
- 입양완료, 입양취소 상세페이지 
- 입양완료 탭에서 파양기능 (동물상태 업데이트 및 입양상태 업데이트)
- 마이페이지 내활동/댓글내역 
어떤 변경 사항이 있나요?
> [24.12.20]입양완료,취소(상세보기,파양), 마이페이지(뎃글내역)

- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/MailDTO2.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
- semi-project/src/main/resources/mappers/emailMapper.xml
- semi-project/src/main/resources/static/sidemenu/mail/css/mailDetail.css
- semi-project/src/main/resources/templates/sidemenu/mail/archived.html
- semi-project/src/main/resources/templates/sidemenu/mail/important.html
- semi-project/src/main/resources/templates/sidemenu/mail/mail.html
- semi-project/src/main/resources/templates/sidemenu/mail/mailDetail.html
- semi-project/src/main/resources/templates/sidemenu/mail/trash.html
> <24.12.20 메일>

- semi-project/src/main/java/com/ohgiraffers/semiproject/approval/controller/ApprovalController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/approval/model/dao/ApprovalMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/approval/model/service/ApprovalService.java
- semi-project/src/main/resources/mappers/approvalFrom.xml
- semi-project/src/main/resources/static/sidemenu/approval/css/approval-style.css
- semi-project/src/main/resources/static/sidemenu/approval/css/vacation-form.css
- semi-project/src/main/resources/static/sidemenu/approval/js/my-approval-list.js
- semi-project/src/main/resources/static/sidemenu/schedule/css/schedule-style.css
- semi-project/src/main/resources/templates/sidemenu/approval/approval.html
- semi-project/src/main/resources/templates/sidemenu/approval/createCac-form.html
- semi-project/src/main/resources/templates/sidemenu/approval/createOverTime-form.html
- semi-project/src/main/resources/templates/sidemenu/approval/createRetirement-form.html
- semi-project/src/main/resources/templates/sidemenu/approval/createVacation-form.html
- semi-project/src/main/resources/templates/sidemenu/approval/myCacRequest.html
- semi-project/src/main/resources/templates/sidemenu/approval/myOverTimeRequest.html
- semi-project/src/main/resources/templates/sidemenu/approval/myRetireMentRequest.html
- semi-project/src/main/resources/templates/sidemenu/approval/myVacRequest.html
#198 
#197 
사용자 결재함이 구현되었습니다
- 기존 관리자 결재함과 UI 및 구조적으로 크게 달라지진 않았지만 그래도 관리자 결재함과 다른 컬러로 구분을 하였습니다
-  결재 목록 리스트는 관리자 결재함은 본인한테 기안이 올라온 리스트들을 전부 확인할 수 있도록 하였지만
사용자 결재함은 본인이 작성한 리스트만 확인할 수 있도록 로직을 변경하였습니다.
- 작성된 기안서가 잘못 작성된 상황이라면 관리자가 승인 및 반려 하기 전에는 삭제가 가능하도록 로직을 구현하였습니다
- 만약 관리자가 승인 및 반려를 처리 하였다면 삭제가 불가능하게 알림창으로 안내될 수 있도록 하였습니다 
어떤 변경 사항이 있나요?
> [24.12.21] 사용자 결재 로직 및 UI 구현 완료

- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/CommentDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/EmployeeDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/EmployeeDTOJOB.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/static/sidemenu/mypage/css/myComments-style.css
- semi-project/src/main/resources/static/sidemenu/mypage/css/myMails-style.css
- semi-project/src/main/resources/static/sidemenu/mypage/css/myPosts-style.css
- semi-project/src/main/resources/static/sidemenu/mypage/css/mypage-style.css
- semi-project/src/main/resources/templates/sidemenu/mypage/myComments.html
- semi-project/src/main/resources/templates/sidemenu/mypage/myMails.html
- semi-project/src/main/resources/templates/sidemenu/mypage/myPosts.html
- semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
#200 
댓글내역에서 내가 쓴 댓글 직원상세페이지로 이동
어떤 변경 사항이 있나요?
> [24.12.22]댓글내역 상세페이지로 이동

- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
- semi-project/src/main/resources/mappers/emailMapper.xml
- semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
- semi-project/src/main/resources/templates/sidemenu/mail/archived.html
- semi-project/src/main/resources/templates/sidemenu/mail/important.html
- semi-project/src/main/resources/templates/sidemenu/mail/mail.html
- semi-project/src/main/resources/templates/sidemenu/mail/mailSent.html
- semi-project/src/main/resources/templates/sidemenu/mail/trash.html
메일 체크박스 선택하고 이동시키는 기능
어떤 변경 사항이 있나요?
> <24.12.23메일이동>

- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
- semi-project/src/main/resources/mappers/emailMapper.xml
- semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
- semi-project/src/main/resources/templates/sidemenu/mail/archived.html
- semi-project/src/main/resources/templates/sidemenu/mail/important.html
- semi-project/src/main/resources/templates/sidemenu/mail/mail.html
- semi-project/src/main/resources/templates/sidemenu/mail/mailSent.html
- semi-project/src/main/resources/templates/sidemenu/mail/trash.html
> 24.12.23이메일이동2

- semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/UserController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerVacationAPIController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerVacationController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dao/ManagerVacationMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/VacationListDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/VacationManagementDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/service/ManagerVacationService.java
- semi-project/src/main/resources/mappers/managerVacationMapper.xml
- semi-project/src/main/resources/static/sidemenu/manager/css/scheduleManagement.css
- semi-project/src/main/resources/static/sidemenu/manager/css/vacationManagement.css
- semi-project/src/main/resources/static/sidemenu/manager/js/scheduleManagement.js
- semi-project/src/main/resources/static/sidemenu/manager/js/vacationManagement.js
- semi-project/src/main/resources/templates/sidemenu/manager/scheduleManagement.html
- semi-project/src/main/resources/templates/sidemenu/manager/vacationManagement.html
https://github.com/1995-s-Project/1995-s_GroupWare/issues/211
https://github.com/1995-s-Project/1995-s_GroupWare/issues/212
직원관리 -> 연차 휴가 생성 및 차감이 구현되었습니다
- 관리자는 근태율에 따라 연차 및 휴가를 생성하고 차감 할 수 있습니다
- 1년 미만의 근속자는 지난달 근태율 100% 만 연차 1개 발생하므로 필터링 기능을 추가하였습니다
- 1년이상 근무자는 80% 이상 작년 근태율을 유지해야만 연차가 발생하므로 필터링 기능을 추가하였습니다
- 사번을 체크하지 않으면 생성 및 차감을 할 수 없도록 하였습니다
- 일 수를 입력하지 않으면 폼을 제출할 수 없도록 하였습니다
- 부서명 및 이름으로 필터링 가능하도록 하였습니다
어떤 변경 사항이 있나요?
> 정근희/직원관리(연차휴가추가생성)

- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/MailDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
- semi-project/src/main/resources/mappers/emailMapper.xml
#216 
이메일 이동 보완할 부분 하는중
어떤 변경 사항이 있나요?
> <24.12.25이메일이동>

- semi-project/src/main/resources/static/sidemenu/manager/js/manager.js
없음
결재 카운트 코드를 수정하였습니다
어떤 변경 사항이 있나요?
> [24.12.26] 결재 카운트 코드 수정

- semi-project/src/main/resources/static/sidemenu/manager/js/manager.js
없음
To-Do List 로직을 수정하였습니다
어떤 변경 사항이 있나요?
> [24.12.27] To-Do 리스트 로직 수정

- semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/UserController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/main/controller/UserInfoController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/controller/ChatController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/controller/MessengerController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dto/ChatDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dto/MessengerDTO.java
- semi-project/src/main/resources/mappers/chatMapper.xml
- semi-project/src/main/resources/mappers/messengerMapper.xml
- semi-project/src/main/resources/static/main/js/user-info.js
- semi-project/src/main/resources/static/sidemenu/messenger/css/messenger-style.css
- semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
- semi-project/src/main/resources/static/sidemenu/schedule/js/user-info.js
- semi-project/src/main/resources/templates/main/main.html
- semi-project/src/main/resources/templates/sidemenu/messenger/messenger.html
없음
채팅 로직 및 UI 구현
어떤 변경 사항이 있나요?
> [24.12.27] 채팅기능 구현중

- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
- semi-project/src/main/resources/mappers/emailMapper.xml
- semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailDetail.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
- semi-project/src/main/resources/templates/sidemenu/mail/archived.html
- semi-project/src/main/resources/templates/sidemenu/mail/important.html
- semi-project/src/main/resources/templates/sidemenu/mail/mail.html
- semi-project/src/main/resources/templates/sidemenu/mail/mailDetail.html
- semi-project/src/main/resources/templates/sidemenu/mail/trash.html
> <24.12.27 이메일css>

- semi-project/src/main/java/com/ohgiraffers/semiproject/board/controller/BoardController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
- semi-project/src/main/resources/templates/sidemenu/mail/mail.html
#234 
이메일 전체선택시 약간의 오류발생 제거
어떤 변경 사항이 있나요?
> <24.12.27 이메일전체선택수정>

- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/controller/AdoptionController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dao/AdoptionMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/service/AdoptionService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
- semi-project/src/main/resources/mappers/animalAdopterMapper.xml
- semi-project/src/main/resources/mappers/animalMapper.xml
- semi-project/src/main/resources/static/sidemenu/adoption/css/adoption-style.css
- semi-project/src/main/resources/templates/sidemenu/adoption/adoption.html
- semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
#237 
입양페이지 - 등록기능구현
어떤 변경 사항이 있나요?
> [24.12.27]입양페이지 - 등록기능구현

- semi-project/src/main/java/com/ohgiraffers/semiproject/config/CustomAccessDeniedHandler.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/config/SecurityConfig.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeAPIController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/UserController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/main/model/dto/UserInfoResponse.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/main/model/service/UserInfoService.java
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/mappers/managerMapper.xml
- semi-project/src/main/resources/static/main/css/main-style.css
- semi-project/src/main/resources/static/main/js/main.js
- semi-project/src/main/resources/static/sidemenu/manager/css/employeeRegister-style.css
- semi-project/src/main/resources/static/sidemenu/manager/js/employeeRegister.js
- semi-project/src/main/resources/static/sidemenu/manager/js/manager.js
- semi-project/src/main/resources/templates/sidemenu/manager/employeeRegister.html
- semi-project/src/main/resources/templates/sidemenu/manager/manager.html
#240 
#241 
사원등록
- 다음 주소 API 를 연동하여 주소를 정확히 입력할 수 있도록 추가 하였습니다
- 프로필 사진 업로드 시 DB에 없는 사원번호가 자동으로 입력되도록 하였습니다
- 값이 하나라도 입력되지 않을 시 제출할 수 없도록 예외처리 하였습니다
관리자페이지
- 대표 직급은 앞에 관리자 권한이 결재를 처리한 경우의 건 수만 표시할 수 있도록 로직을 수정하였습니다
- 관리자가 먼저 처리하지 않을 시 대표 직급은 결재 대기건에 대해 카운트가 추가 되지 않습니다
현재 로그인한 정보의 권한을 체크하여 USER 권한일 시 관리자 전용 버튼이 보이지 않도록 하였고
만약 ADMIN 권한일 시 관리자 전용 버튼이 나타나도록 추가하였습니다
어떤 변경 사항이 있나요?
- **대표는 관리자가 먼저 처리한 건이 없다면 결재 대기 카운트가 되지 않습니다**
- 만약 관리자가 처리된 건이 있다면 카운트가 됩니다
- 관리자 측에서 반려 처리를 한다면 카운트가 되지 않습니다(대표까지 반려할 필요는 없기 때문)
- 이렇게 대표가 승인 및 반려 해야 하는 건에 대해서만 확인 가능 합니다
- 일반 직급은 관리자 전용 버튼이 보이지 않도록 하였습니다
- 관리자 직급은 관리자 전용 버튼이 보이도록 하였습니다
> [24.12.29] 결재로직수정,사원등록 주소API 연동, 자동 사번부여, 권한체크 후 관리자 버튼 숨기거나 보이기

- semi-project/src/main/java/com/ohgiraffers/semiproject/board/controller/BoardController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/dao/BoardMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/service/BoardService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/mappers/employeeMapper.xml
- semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
- semi-project/src/main/resources/templates/sidemenu/board/board.html
- semi-project/src/main/resources/templates/sidemenu/board/regist.html
- semi-project/src/main/resources/templates/sidemenu/board/search.html
- semi-project/src/main/resources/templates/sidemenu/board/title.html
- semi-project/src/main/resources/templates/sidemenu/board/update.html
- semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
- semi-project/src/main/resources/templates/sidemenu/employee/employee.html
- semi-project/src/main/resources/templates/sidemenu/employee/search.html
- semi-project/src/main/resources/templates/sidemenu/mail/mailDetail.html
- semi-project/src/main/resources/templates/sidemenu/mail/mailSent.html
발표전정리
발표전 에러있는지 확인
어떤 변경 사항이 있나요?
> <24.12.30발표전정리>

- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/controller/AdoptionController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/controller/MyPageController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/model/service/MyPageService.java
- semi-project/src/main/resources/mappers/animalMapper.xml
- semi-project/src/main/resources/static/sidemenu/animals/css/animalDetail-style.css
- semi-project/src/main/resources/templates/sidemenu/adoption/adoptingDetail.html
- semi-project/src/main/resources/templates/sidemenu/animals/animals.html
- semi-project/src/main/resources/templates/sidemenu/animals/detailAnimal.html
- semi-project/src/main/resources/templates/sidemenu/animals/insert.html
- semi-project/src/main/resources/templates/sidemenu/mypage/myComments.html
- semi-project/src/main/resources/templates/sidemenu/mypage/myPosts.html
- semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
- semi-project/src/main/resources/templates/sidemenu/mypage/settingPass.html
#244 
입양, 구조동물, 마이페이지 예외처리, url 정리, 동물상세페이지 css
어떤 변경 사항이 있나요?
> [24.12.30]입양, 구조동물, 마이페이지 예외처리

- semi-project/src/main/resources/static/sidemenu/board/js/board.js
- semi-project/src/main/resources/static/sidemenu/manager/js/manager.js
- semi-project/src/main/resources/templates/sidemenu/board/board.html
없음
전사 게시판 코드 일부 수정하였습니다
어떤 변경 사항이 있나요?
> [24.12.30] 코드일부수정

- semi-project/src/main/resources/static/main/js/slide-bar.js
없음
메인 페이지 슬라이드 바 코드 일부 수정하였습니다
어떤 변경 사항이 있나요?
> [24.12.30] 슬라이드바 코드 일부수정

- semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
- semi-project/src/main/resources/templates/sidemenu/adoption/adoptCanceledDetail.html
- semi-project/src/main/resources/templates/sidemenu/adoption/adoptCompletedDetail.html
- semi-project/src/main/resources/templates/sidemenu/board/title.html
없음
발표 후 수정 필요해서 최근꺼 머지 하겠습니다
어떤 변경 사항이 있나요?
> [24.12.30] 발표 후 수정 필요

- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dao/AdoptionMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dto/AdoptionDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/service/AdoptionService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/controller/MyPageController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/model/service/MyPageService.java
- semi-project/src/main/resources/mappers/animalAdopterMapper.xml
- semi-project/src/main/resources/static/sidemenu/mypage/css/calendar-style.css
- semi-project/src/main/resources/static/sidemenu/mypage/js/calendar.js
- semi-project/src/main/resources/templates/sidemenu/adoption/adoptCanceledDetail.html
- semi-project/src/main/resources/templates/sidemenu/adoption/adoptCompletedDetail.html
- semi-project/src/main/resources/templates/sidemenu/adoption/adoptingDetail.html
- semi-project/src/main/resources/templates/sidemenu/adoption/adoption.html
- semi-project/src/main/resources/templates/sidemenu/animals/animals.html
- semi-project/src/main/resources/templates/sidemenu/animals/insert.html
- semi-project/src/main/resources/templates/sidemenu/mypage/calender.html
- semi-project/src/main/resources/templates/sidemenu/mypage/myComments.html
- semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
- semi-project/src/main/resources/templates/sidemenu/mypage/settingPass.html
#249 
마이페이지 캘린더 기능추가 
마이페이지 주소변경 - 상세주소추가
동물, 입양 예외처리
어떤 변경 사항이 있나요?
> [24.12.30]마이페이지캘린더, 상세주소추가, 동물, 입양 예외처리

- semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/service/AdoptionService.java
> [24.12.30]마이페이지-게시글에러 수정

- semi-project/src/main/resources/templates/sidemenu/manager/manager.html
없음
관리자 페이지 대시보드 코드 일부수정
어떤 변경 사항이 있나요?
> [24.12.30] 관리자페이지 날짜 포맷팅 코드 수정

- semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
메신저 css수정, 메신저 사용자목록 선택시 대화방 제목 직급, 부서 추가 
기존 코드번호로 나오던 채팅 상대 에 이름 부서 직급 추가
> [241230] 메신저 css수정, 메신저 사용자목록 선택시 대화방 제목 직급, 부서 추가

- semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/controller/ChatController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dao/ChatMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dto/ChatDTO.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/service/ChatService.java
- semi-project/src/main/resources/mappers/chatMapper.xml
- semi-project/src/main/resources/static/sidemenu/messenger/css/messenger-style.css
- semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
없음
안 읽은 메세지 로직을 추가하였습니다
어떤 변경 사항이 있나요?
> [24.12.31] 안읽은 메세지 로직 추가

- semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/controller/ChatController.java
- semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
없음
채팅 로직 일부 수정하였습니다
어떤 변경 사항이 있나요?
> [24.12.31] 채팅로직 일부수정

- semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
채팅알림기능추가
채팅 수신시 발신자가 보낸 메세지 수만큼 알림기능 추가 
> 241230 채팅알림기능추가

- semi-project/src/main/resources/static/sidemenu/messenger/css/messenger-style.css
- semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
> 241230 채팅기능완료

- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerApprovalController.java
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/static/sidemenu/employee/css/employee-style.css
- semi-project/src/main/resources/static/sidemenu/employee/css/empmanagement.css
- semi-project/src/main/resources/static/sidemenu/employee/js/empManagement.js
- semi-project/src/main/resources/templates/sidemenu/employee/employee.html
- semi-project/src/main/resources/templates/sidemenu/employee/management.html
없음
조직도 로직 및 css 수정
어떤 변경 사항이 있나요?
> [24.12.31] 조직도 수정

- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/static/sidemenu/employee/css/customer.css
- semi-project/src/main/resources/static/sidemenu/employee/css/dog.css
- semi-project/src/main/resources/static/sidemenu/employee/css/logistics.css
- semi-project/src/main/resources/static/sidemenu/employee/css/marketing.css
- semi-project/src/main/resources/static/sidemenu/employee/css/sales.css
- semi-project/src/main/resources/templates/sidemenu/employee/customer.html
- semi-project/src/main/resources/templates/sidemenu/employee/dog.html
- semi-project/src/main/resources/templates/sidemenu/employee/employee.html
- semi-project/src/main/resources/templates/sidemenu/employee/logistics.html
- semi-project/src/main/resources/templates/sidemenu/employee/management.html
- semi-project/src/main/resources/templates/sidemenu/employee/marketing.html
- semi-project/src/main/resources/templates/sidemenu/employee/sales.html
> <24.12.31직원정보css>

- semi-project/src/main/resources/static/sidemenu/manager/css/vacationManagement.css
없음
관리자 페이지 -> 연차&휴가 관리 CSS 일부 수정하였습니다
어떤 변경 사항이 있나요?
> [25.01.01] 연차&휴가 관리 CSS 일부 수정

- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
- semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
- semi-project/src/main/resources/mappers/emailMapper.xml
- semi-project/src/main/resources/mappers/empMapper.xml
- semi-project/src/main/resources/static/sidemenu/employee/css/customer.css
- semi-project/src/main/resources/static/sidemenu/employee/css/dog.css
- semi-project/src/main/resources/static/sidemenu/employee/css/empmanagement.css
- semi-project/src/main/resources/static/sidemenu/employee/css/logistics.css
- semi-project/src/main/resources/static/sidemenu/employee/css/marketing.css
- semi-project/src/main/resources/static/sidemenu/employee/css/sales.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailDetail.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
- semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
- semi-project/src/main/resources/templates/sidemenu/employee/customer.html
- semi-project/src/main/resources/templates/sidemenu/employee/dog.html
- semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
- semi-project/src/main/resources/templates/sidemenu/employee/logistics.html
- semi-project/src/main/resources/templates/sidemenu/employee/management.html
- semi-project/src/main/resources/templates/sidemenu/employee/marketing.html
- semi-project/src/main/resources/templates/sidemenu/employee/sales.html
- semi-project/src/main/resources/templates/sidemenu/mail/archived.html
- semi-project/src/main/resources/templates/sidemenu/mail/important.html
- semi-project/src/main/resources/templates/sidemenu/mail/mail.html
- semi-project/src/main/resources/templates/sidemenu/mail/mailDetail.html
- semi-project/src/main/resources/templates/sidemenu/mail/mailSent.html
- semi-project/src/main/resources/templates/sidemenu/mail/trash.html
#269 
발표전 에러 확인 및 수정
어떤 변경 사항이 있나요?
> <25.01.02최종수정>

- semi-project/src/main/java/com/ohgiraffers/semiproject/config/WebSocketConfig.java
없음
웹소켓 로직 코드 일부 수정하였습니다
어떤 변경 사항이 있나요?
> [25.01.01] 웹소켓 로직 일부 수정

- semi-project/src/main/resources/static/sidemenu/employee/css/empmanagement.css
- semi-project/src/main/resources/templates/sidemenu/board/board.html
- semi-project/src/main/resources/templates/sidemenu/board/search.html
#270 
발표전 최종수정2
어떤 변경 사항이 있나요?
> <25.01.02발표전최종수정>

- semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleController.java
- semi-project/src/main/resources/templates/sidemenu/animals/animals.html
#272 
구조동물 이미지 코드 수정
어떤 변경 사항이 있나요?
> [24.01.02]구조동물 이미지 코드 수정

- semi-project/src/main/java/com/ohgiraffers/semiproject/config/WebSocketConfig.java
- semi-project/src/main/resources/templates/sidemenu/animals/animals.html
- semi-project/src/main/resources/templates/sidemenu/schedule/schedule.html
> [25.01.01] 구조동물 로직 수정

- semi-project/src/main/resources/templates/sidemenu/board/title.html
#272 
발표전 최종수정 3
어떤 변경 사항이 있나요?
> <25.01.02 발표전최종수정3>

- semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
- semi-project/src/main/resources/templates/home.html
> [25.01.02] 채팅 로직 수정

- semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
> [250102]sout 삭제

- semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/HomeController.java
- semi-project/src/main/resources/templates/sidemenu/approval/approval.html
> [25.01.02] 경로 수정
